version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./fastapi_app/Dockerfile
    restart: always
    ports:
     - "5001:5001"
    depends_on:
      - redis
  worker:
    build:
      context: task_queue
      dockerfile: Dockerfile
    depends_on:
      - redis
  redis:
    image: redis:5.0
